
import { User, Coach, MarketItem, UserRole, Language, Goal, DailyPlan, SiteConfig, KnowledgeBaseItem } from './types';

export const USERS: User[] = [
  { id: 'admin1', name: 'Admin', email: 'admin@ny11.com', phone: '000000000', role: UserRole.ADMIN, avatar: 'https://i.pravatar.cc/150?u=admin1', password: 'admin123' },
  { id: 'user1', name: 'John Doe', email: 'john@test.com', phone: '123456789', role: UserRole.USER, age: 30, weight: 80, height: 180, goal: Goal.MAINTENANCE, avatar: 'https://i.pravatar.cc/150?u=user1' },
];

export const COACHES: Coach[] = [
    { 
      id: 'coach1', 
      name: 'Sarah Ahmed', 
      specialty: 'Nutrition Specialist', 
      avatar: 'https://picsum.photos/id/1027/200/200',
      bio: 'Sarah is a certified nutritionist with a passion for helping people discover the power of healthy eating. She believes in creating sustainable lifestyle changes, not restrictive diets.',
      experienceYears: 8,
      clientsHelped: 500
    },
    { 
      id: 'coach2', 
      name: 'Mike Thompson', 
      specialty: 'Fitness & Strength', 
      avatar: 'https://picsum.photos/id/1005/200/200',
      bio: 'A former athlete, Mike specializes in strength training and functional fitness. He helps clients build strength, improve mobility, and achieve peak physical performance.',
      experienceYears: 10,
      clientsHelped: 750
    },
    { 
      id: 'coach3', 
      name: 'Fatima Ali', 
      specialty: 'Wellness Coach', 
      avatar: 'https://picsum.photos/id/1011/200/200',
      bio: 'Fatima takes a holistic approach to health, focusing on mind-body connection. She helps clients with stress management, mindful eating, and overall well-being.',
      experienceYears: 6,
      clientsHelped: 400
    },
];

export const DEFAULT_KNOWLEDGE_BASE: KnowledgeBaseItem[] = [
    { id: 'kb1', question: 'How much water should I drink?', answer: 'It is generally recommended to drink at least 8 glasses (about 2 liters) of water a day, but individual needs vary based on activity level and climate.', keywords: ['water', 'drink', 'hydration'] },
    { id: 'kb2', question: 'What is a good breakfast for weight loss?', answer: 'A high-protein breakfast like oatmeal with berries, eggs with avocado, or greek yogurt is excellent for weight loss.', keywords: ['breakfast', 'weight', 'loss', 'food'] },
    { id: 'kb3', question: 'How do I build muscle?', answer: 'To build muscle, focus on hypertrophy training (8-12 reps), eat a protein-rich diet, and ensure you are getting enough rest.', keywords: ['muscle', 'build', 'strength'] },
    { id: 'kb4', question: 'Can I cancel my subscription?', answer: 'Yes, you can manage your subscription settings in your profile page under the "Settings" tab.', keywords: ['cancel', 'subscription', 'plan'] },
    { id: 'kb5', question: 'Hi', answer: 'Hello! I am NY11 AI Coach. How can I help you with your health journey today?', keywords: ['hello', 'hi', 'hey'] },
];

export const MARKET_ITEMS: MarketItem[] = [
    { 
      id: 'm3', 
      name: 'Chicken Salad', 
      description: 'A nutritious and fresh chicken salad perfect for any time.',
      summary: 'HIGH PROTEIN MEAL',
      price: 12.50, 
      image: 'https://i.ibb.co/NdWmCJTb/image.png', 
      category: 'lunch',
      ingredients: 'Fresh tomatoes, cucumbers, grilled chicken breast, lettuce, and almonds. Dressing: Fresh lemon juice and a pinch of salt.',
      nutrition: {
        servingSize: '1 cup (salad)',
        energy: '80 kJ',
        protein: '23 g',
        carbs: '10 g',
        fat: '15 g'
      },
      caution: 'this item contains items that may cause allergies such as nuts.'
    },
    { id: 'm1', name: 'Oatmeal with Almonds', description: 'A light and energetic start to your day.', price: 8.50, image: 'https://picsum.photos/id/1080/400/300', category: 'breakfast' },
    { id: 'm2', name: 'Avocado Toast', description: 'Fresh avocado on whole wheat bread with seeds.', price: 9.00, image: 'https://picsum.photos/id/493/400/300', category: 'breakfast' },
    { id: 'm4', name: 'Quinoa Bowl', description: 'A hearty bowl of quinoa with roasted vegetables.', price: 11.00, image: 'https://picsum.photos/id/25/400/300', category: 'lunch' },
    { id: 'm5', name: 'Salmon with Asparagus', description: 'Pan-seared salmon served with fresh asparagus.', price: 15.00, image: 'https://picsum.photos/id/31/400/300', category: 'dinner' },
    { id: 'm6', name: 'Turkey Meatballs', description: 'Lean turkey meatballs with zucchini noodles.', price: 13.50, image: 'https://picsum.photos/id/48/400/300', category: 'dinner' },
    { id: 'd1', name: 'Green Smoothie', description: 'A refreshing blend of spinach, kale, and fruit.', price: 6.50, image: 'https://picsum.photos/id/40/400/300', category: 'drink' },
    { id: 'd2', name: 'Fresh Orange Juice', description: '100% pure squeezed orange juice.', price: 5.00, image: 'https://picsum.photos/id/42/400/300', category: 'drink' },
    { id: 's1', name: 'Greek Yogurt with Honey', description: 'High protein snack for muscle recovery.', price: 4.50, image: 'https://picsum.photos/id/41/400/300', category: 'snack' },
    { id: 's2', name: 'Nut Mix', description: 'A selection of raw, unsalted nuts.', price: 6.00, image: 'https://picsum.photos/id/1016/400/300', category: 'snack' },
];

export const ONBOARDING_BACKGROUNDS = [
    'https://picsum.photos/id/1060/1200/800',
    'https://picsum.photos/id/102/1200/800',
];

export const BANNER_IMAGES = [
    'https://i.ibb.co/NdWmCJTb/image.png',
    'https://i.ibb.co/5xFDgQ2c/image.png',
    'https://i.ibb.co/hxbVf4f7/image.png',
];

export const DEFAULT_SITE_CONFIG: SiteConfig = {
    heroImage: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80',
};

export const GOAL_PLANS: Record<Goal, DailyPlan> = {
  [Goal.WEIGHT_LOSS]: {
    breakfast: [{ name: 'Oatmeal with Berries', calories: 300, completed: false, image: 'https://picsum.photos/id/1080/400/300', description: 'A warm bowl of oatmeal topped with fresh mixed berries.' }],
    lunch: [{ name: 'Grilled Chicken Salad', calories: 400, completed: false, image: 'https://picsum.photos/id/23/400/300', description: 'Lean grilled chicken breast over a bed of fresh greens and vegetables.' }],
    dinner: [{ name: 'Baked Salmon with Asparagus', calories: 450, completed: false, image: 'https://picsum.photos/id/31/400/300', description: 'Nutrient-rich baked salmon served with a side of steamed asparagus.' }],
    snacks: [{ name: 'Greek Yogurt', calories: 150, completed: false, image: 'https://picsum.photos/id/41/400/300', description: 'A cup of plain Greek yogurt.' }],
    exercises: [{ name: '45 min Cardio', duration: '45 min', completed: false }],
  },
  [Goal.WEIGHT_GAIN]: {
    breakfast: [{ name: 'Scrambled Eggs with Avocado Toast', calories: 500, completed: false, image: 'https://picsum.photos/id/1078/400/300', description: 'Three scrambled eggs with two slices of whole-wheat toast topped with avocado.' }],
    lunch: [{ name: 'Beef Burrito Bowl', calories: 700, completed: false, image: 'https://picsum.photos/id/1015/400/300', description: 'A hearty bowl with brown rice, black beans, beef, and cheese.' }],
    dinner: [{ name: 'Pasta with Meat Sauce', calories: 650, completed: false, image: 'https://picsum.photos/id/1074/400/300', description: 'A generous portion of pasta with a rich, homemade meat sauce.' }],
    snacks: [{ name: 'Handful of Almonds & a Banana', calories: 300, completed: false, image: 'https://picsum.photos/id/1016/400/300', description: 'A healthy, calorie-dense snack.' }],
    exercises: [{ name: '60 min Full Body', duration: '60 min', completed: false }],
  },
  [Goal.MUSCLE_BUILD]: {
    breakfast: [{ name: 'Protein Pancakes', calories: 450, completed: false, image: 'https://picsum.photos/id/1025/400/300', description: 'Fluffy pancakes made with protein powder, served with syrup.' }],
    lunch: [{ name: 'Chicken Breast with Quinoa & Broccoli', calories: 600, completed: false, image: 'https://picsum.photos/id/1028/400/300', description: 'A classic muscle-building meal with lean protein and complex carbs.' }],
    dinner: [{ name: 'Steak with Sweet Potato', calories: 700, completed: false, image: 'https://picsum.photos/id/1035/400/300', description: 'A juicy steak served with a baked sweet potato for energy.' }],
    snacks: [{ name: 'Protein Shake', calories: 250, completed: false, image: 'https://picsum.photos/id/106/400/300', description: 'A quick and easy protein shake to fuel muscle recovery.' }],
    exercises: [{ name: 'Push Day', reps: '3-4 sets of 8-12', completed: false }],
  },
  [Goal.FITNESS]: {
    breakfast: [{ name: 'Smoothie with Spinach and Fruit', calories: 350, completed: false, image: 'https://picsum.photos/id/40/400/300', description: 'A vibrant smoothie packed with vitamins and minerals.' }],
    lunch: [{ name: 'Tuna Wrap', calories: 450, completed: false, image: 'https://picsum.photos/id/43/400/300', description: 'A whole-wheat wrap filled with tuna salad and fresh lettuce.' }],
    dinner: [{ name: 'Turkey Meatballs with Zucchini Noodles', calories: 500, completed: false, image: 'https://picsum.photos/id/48/400/300', description: 'A light yet satisfying dinner to keep you energized.' }],
    snacks: [{ name: 'Apple with Peanut Butter', calories: 200, completed: false, image: 'https://picsum.photos/id/51/400/300', description: 'A balanced snack with fiber and healthy fats.' }],
    exercises: [{ name: '20 min HIIT', duration: '20 min', completed: false }],
  },
  [Goal.MAINTENANCE]: {
    breakfast: [{ name: 'Everything Bagel with Cream Cheese', calories: 400, completed: false, image: 'https://picsum.photos/id/55/400/300', description: 'A classic breakfast to start your day.' }],
    lunch: [{ name: 'Leftover Turkey Meatballs', calories: 500, completed: false, image: 'https://picsum.photos/id/48/400/300', description: 'Easy and delicious leftovers from last night.' }],
    dinner: [{ name: 'Homemade Pizza', calories: 600, completed: false, image: 'https://picsum.photos/id/58/400/300', description: 'A balanced homemade pizza with your favorite toppings.' }],
    snacks: [{ name: 'Popcorn', calories: 150, completed: false, image: 'https://picsum.photos/id/60/400/300', description: 'A light snack for when you feel peckish.' }],
    exercises: [{ name: '30 min Jogging', duration: '30 min', completed: false }],
  },
};

export const TRANSLATIONS = {
  [Language.EN]: {
    // General
    appName: 'ny11',
    save: 'Save',
    close: 'Close',
    calories: 'Calories',
    next: 'Next',
    back: 'Back',
    guest: 'Guest',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    aiNutritionist: 'NY11 AI Coach',

    // Landing Page
    aboutUsTitle: 'About ny11',
    aboutUsDesc: 'ny11 is more than just a nutrition app. We are a digital health sanctuary designed to bridge the gap between complex science and your daily lifestyle. Our mission is to empower you with expert knowledge and healthy tools to become the best version of yourself.',
    statsTitle: 'ny11 in Numbers',
    statClients: 'Happy Clients',
    statPlans: 'Custom Plans',
    statExperts: 'Certified Experts',
    statSupport: 'Support Hours',
    featuredProducts: 'Featured Healthy Choices',
    testimonialsTitle: 'What Our Users Say',
    ourExpertsShort: 'Meet Our Certified Experts',

    // Market Categories
    all: 'All',
    cat_breakfast: 'Breakfast',
    cat_lunch: 'Lunch',
    cat_dinner: 'Dinner',
    cat_drink: 'Drinks',
    cat_snack: 'Snacks',

    // Hero & Web
    heroTitle: 'Transform Your Health with ny11',
    heroSubtitle: 'Connect with certified nutrition and fitness experts to get a personalized plan tailored just for you. Start your journey today.',
    getStarted: 'Get Started',
    home: 'Home',
    about: 'About Us',
    contact: 'Contact',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    copyright: '© 2024 ny11. All rights reserved.',
    footerDesc: 'Your comprehensive platform for health, nutrition, and wellness.',

    // Onboarding & Auth
    welcome: 'Welcome to ny11',
    chooseLang: 'Choose your language',
    stepIndicator: 'Step {current} of {total}',
    whatsYourName: "What's your full name?",
    namePlaceholder: 'Enter your full name',
    nameInfo: "Your name helps us personalize your experience.",
    whatsYourEmail: "What's your email?",
    emailPlaceholder: 'Enter your email',
    emailInfo: "Your email will be used to log in and receive notifications.",
    whatsYourPhone: "What's your phone number?",
    phonePlaceholder: 'Enter your phone number',
    phoneInfo: "Your phone number helps us with account verification and support.",
    whatsYourAge: "What's your age?",
    agePlaceholder: 'e.g., 30',
    ageInfo: "Your age helps us accurately calculate your nutritional needs.",
    whatsYourWeight: "What's your weight? (kg)",
    weightPlaceholder: 'e.g., 80',
    weightInfo: "Your weight is a key factor in creating an effective health plan.",
    whatsYourHeight: "What's your height? (cm)",
    heightPlaceholder: 'e.g., 180',
    heightInfo: "Your height is used to calculate your BMI and personalize your plan.",
    yourGoal: 'What is your primary goal?',
    goalInfo: "Selecting a goal allows us to tailor your daily meals and exercises.",
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    login: 'Login',
    register: 'Register',
    registerNewAccount: 'Create a new account',
    loginToYourAccount: 'Login to your account',
    or: 'or',
    completeRegistration: 'Complete Registration',
    welcomeGuestTitle: 'Welcome to NY11',
    welcomeGuestBody: "To get your personalized plan, please log in or create a new account. We'll guide you through a few quick steps to set up your profile.",
    loginOrRegister: 'Login / Register',
    loginToContinue: 'Please log in to use this feature.',
    registrationNote: 'All the information you provide will be used by our experts to offer a distinguished and correct service. Please provide accurate data.',
    
    // Nav
    dashboard: 'Dashboard',
    experts: 'Experts',
    activeChats: 'Chats',
    market: 'Market',
    stats: 'Statistics',
    settings: 'Settings',
    
    // Dashboard
    myProfile: 'My Profile',
    age: 'Age',
    weight: 'Weight',
    height: 'Height',
    todaysPlan: "Today's Plan",
    weightLoss: 'Weight Loss',
    weightGain: 'Weight Gain',
    muscleBuild: 'Muscle Building',
    fitness: 'General Fitness',
    maintenance: 'Maintain Weight',
    finishSetup: 'Finish Setup',
    mealDetails: 'Meal Details',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    snacks: 'Snacks',
    exercises: 'Exercises',
    setupProfileTitle: "Let's set up your profile",
    setupProfileSubtitle: 'Based on this information, we will tailor your daily meals and exercises.',
    generatingPlan: 'Generating Your Plan...',
    generatingPlanDesc: "We're personalizing your daily schedule based on your goals.",
    
    // Chat
    connectWithExpert: 'Connect with an Expert',
    connectWithExpertDesc: 'Choose a specialist to start your personalized health journey.',
    whyAnExpert: 'Why an Expert?',
    whyAnExpertDesc: 'Our certified experts provide 1-on-1 guidance tailored to your unique body and goals. Get a plan that works, accountability, and the motivation you need to succeed.',
    viewProfile: 'View Profile',
    backToExperts: 'Back to Experts',
    yearsExp: 'Years Exp.',
    clientsHelped: 'Clients Helped',
    startChat: 'Start Chat',
    typeAMessage: 'Type a message...',
    serviceQuote: 'Service Quote',
    accept: 'Accept',
    decline: 'Decline',
    yourActiveChats: 'Your Active Chats',
    selectAChat: 'Select a conversation to continue.',
    
    // Market
    shoppingCart: 'Shopping Cart',
    cartIsEmpty: 'Your cart is empty.',
    total: 'Total:',
    checkout: 'Checkout',
    add: 'Add',
    ingredients: 'Ingredients',
    nutritionFacts: 'Nutrition Facts',
    caution: 'Caution',
    servingSize: 'Serving size',
    energy: 'Energy',
    protein: 'Protein',
    carbohydrates: 'Carbohydrates',
    fat: 'Fat',
    addToCart: 'Add to Cart',

    // Stats
    yourProgress: 'Your Progress',
    overallAdherence: 'Overall Adherence',
    weeklyAdherence: 'Weekly Adherence',
    rechartsPlaceholder: 'Chart will be rendered here with Recharts library.',
    
    // Settings
    profileInfo: 'Profile Information',
    name: 'Name',
    email: 'Email',
    preferences: 'Preferences',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    language: 'Language',
    english: 'English',
    arabic: 'العربية',
    logout: 'Logout',
    deleteAccount: 'Delete Account',
    deleteAccountConfirm: 'Are you sure you want to delete your account? This action is permanent and cannot be undone.',
    accountDeleted: 'Account deleted successfully.',
    testNotification: 'Test Notification',
    
    // Notifications
    newMessageFrom: 'New message from {name}',
    planUpdatedTitle: 'Plan Updated!',
    planUpdatedBody: 'Your new plan is available on your dashboard.',
    appointmentReminderTitle: 'Upcoming Appointment',
    appointmentReminderBody: 'You have a meeting with your coach in 15 minutes.',

    // Admin Dashboard
    adminDashboard: 'Admin Dashboard',
    accountManagement: 'Account Management',
    coachManagement: 'Coach Management',
    storeManagement: 'Store Management',
    paymentManagement: 'Payment Management',
    contentManagement: 'Content Management',
    aiConfig: 'AI Coach Config',
    users: 'Users',
    coaches: 'Coaches',
    existingCoaches: 'Existing Coaches',
    addNewCoach: 'Add New Coach',
    specialty: 'Specialty',
    bio: 'Bio',
    experience: 'Experience (Years)',
    clients: 'Clients',
    avatarUrl: 'Avatar URL',
    addNewItem: 'Add New Item',
    itemName: 'Item Name',
    description: 'Description',
    price: 'Price',
    imageUrl: 'Image URL',
    category: 'Category',
    meal: 'Meal',
    drink: 'Drink',
    addCoach: 'Add Coach',
    addItem: 'Add Item',
    updateItem: 'Update Item',
    paymentsInfo: 'Payment management features are coming soon.',
    confirmDelete: 'Are you sure you want to delete this item?',
    bannerImages: 'Banner Images',
    addNewImage: 'Add New Image',
    textContentManagement: 'Text Content Management',
    englishContent: 'English Content',
    arabicContent: 'Arabic Content',
    roadmap: 'Roadmap',
    roadmapTitle: 'NY11 Application Roadmap',
    exportPdf: 'Export as PDF',
    q1Title: 'Q1 2024: Foundation & MVP',
    q1Desc: 'Launch of core UI/UX, User Profiles, Basic Market, and initial Expert Chat system.',
    q2Title: 'Q2 2024: Financial & Technical Integration',
    q2Desc: 'Full Payment Gateway (Visa/Mastercard), Real-time Socket.io Chat, and Advanced Push Notifications.',
    q3Title: 'Q3 2024: AI & Personalization',
    q3Desc: 'AI Meal Analysis (Vision API), Smart Auto-Plan Generation based on bio-metrics, Video/Voice Calls.',
    q4Title: 'Q4 2024: Community & Expansion',
    q4Desc: 'Community Challenges, Leaderboards, Wearable Integration (Apple Health/Google Fit), Native Mobile Apps.',
    homePageManagement: 'Home Page Management',
    manageHeroTitle: 'Hero Title',
    manageHeroSubtitle: 'Hero Subtitle',
    heroImage: 'Hero Image URL',
    footerManagement: 'Footer Management',
    manageFooterDesc: 'Footer Description',
    footerCopyright: 'Copyright Text',
    enText: 'English Text',
    arText: 'Arabic Text',
    updateCoach: 'Update Coach',
    editCoach: 'Edit Coach',
    
    // AI Admin
    question: 'Question',
    answer: 'Answer',
    keywords: 'Keywords (comma separated)',
    addNewQA: 'Add New Q&A',
    existingQA: 'Existing Q&A Pairs',
    addQA: 'Add Pair',
    updateQA: 'Update Pair',

    // Guided Tour
    tourWelcomeTitle: 'Welcome to NY11!',
    tourWelcomeBody: "Let's take a quick tour to show you around the key features of the app.",
    tourWelcomeBodyGuest: "Let's take a quick tour to see what you can do. To unlock your personalized plan, you'll need to create an account.",
    tourPlanTitle: "Your Daily Plan",
    tourPlanBody: "Here you'll find your personalized meals and exercises for the day. Check them off as you go!",
    tourLoginPromptTitle: "Your Personalized Plan",
    tourLoginPromptBody: "After you log in, your daily meals and exercises will appear right here. It all starts with creating your profile!",
    tourNavTitle: "Easy Navigation",
    tourNavBody: "Use this bar to switch between the main sections of the app anytime.",
    tourExpertsTitle: "Find an Expert",
    tourExpertsBody: "Browse our certified experts and start a conversation to get a personalized health plan.",
    tourMarketTitle: "Healthy Market",
    tourMarketBody: "Order healthy meals and drinks prepared by our kitchen, delivered right to you.",
    tourSettingsTitle: "Manage Settings",
    tourSettingsBody: "Update your profile, change the theme, and manage your preferences here.",
    tourFinish: "Finish",
    tourSkip: "Skip",
  },
  [Language.AR]: {
    // General
    appName: 'ny11',
    save: 'حفظ',
    close: 'إغلاق',
    calories: 'السعرات الحرارية',
    next: 'التالي',
    back: 'رجوع',
    guest: 'زائر',
    edit: 'تعديل',
    delete: 'حذف',
    cancel: 'إلغاء',
    saveChanges: 'حفظ التغييرات',
    aiNutritionist: 'مدرب NY11 الذكي',

    // Landing Page
    aboutUsTitle: 'من نحن - ny11',
    aboutUsDesc: 'ny11 هو أكثر من مجرد تطبيق تغذية. نحن ملاذ صحي رقمي مصمم لسد الفجوة بين العلوم المعقدة وأسلوب حياتك اليومي. مهمتنا هي تمكينك بالمعرفة الخبيرة والأدوات الصحية لتصبح أفضل نسخة من نفسك.',
    statsTitle: 'ny11 بالأرقام',
    statClients: 'عميل سعيد',
    statPlans: 'خطة مخصصة',
    statExperts: 'خبير معتمد',
    statSupport: 'ساعة دعم',
    featuredProducts: 'خيارات صحية مميزة',
    testimonialsTitle: 'ماذا يقول مستخدمونا',
    ourExpertsShort: 'تعرف على خبرائنا المعتمدين',

    // Market Categories
    all: 'الكل',
    cat_breakfast: 'إفطار',
    cat_lunch: 'غداء',
    cat_dinner: 'عشاء',
    cat_drink: 'مشروبات',
    cat_snack: 'سناكس',

    // Hero & Web
    heroTitle: 'غيّر حياتك الصحية مع ny11',
    heroSubtitle: 'تواصل مع خبراء التغذية واللياقة البدنية المعتمدين للحصول على خطة مخصصة لك. ابدأ رحلتك اليوم.',
    getStarted: 'ابدأ الآن',
    home: 'الرئيسية',
    about: 'من نحن',
    contact: 'اتصل بنا',
    privacy: 'سياسة الخصوصية',
    terms: 'شروط الخدمة',
    copyright: '© 2024 ny11. جميع الحقوق محفوظة.',
    footerDesc: 'منصتك الشاملة للصحة والتغذية واللياقة البدنية.',

    // Onboarding & Auth
    welcome: 'أهلاً بك في ny11',
    chooseLang: 'اختر لغتك',
    stepIndicator: 'خطوة {current} من {total}',
    whatsYourName: "ما هو اسمك الكامل؟",
    namePlaceholder: 'أدخل اسمك الكامل',
    nameInfo: "يساعدنا اسمك في تخصيص تجربتك.",
    whatsYourEmail: "ما هو بريدك الإلكتروني؟",
    emailPlaceholder: 'أدخل بريدك الإلكتروني',
    emailInfo: "سيتم استخدام بريدك الإلكتروني لتسجيل الدخول وتلقي الإشعارات.",
    whatsYourPhone: "ما هو رقم هاتفك؟",
    phonePlaceholder: 'أدخل رقم هاتفك',
    phoneInfo: "يساعدنا رقم هاتفك في التحقق من الحساب وتقديم الدعم.",
    whatsYourAge: 'كم عمرك؟',
    agePlaceholder: 'مثال، 30',
    ageInfo: "يساعدنا عمرك في حساب احتياجاتك الغذائية بدقة.",
    whatsYourWeight: 'ما هو وزنك؟ (كجم)',
    weightPlaceholder: 'مثال، 80',
    weightInfo: "وزنك عامل رئيسي في إنشاء خطة صحية فعالة.",
    whatsYourHeight: 'ما هو طولك؟ (سم)',
    heightPlaceholder: 'مثال، 180',
    heightInfo: "يستخدم طولك لحساب مؤشر كتلة الجسم وتخصيص خطتك.",
    yourGoal: 'ما هو هدفك الأساسي؟',
    goalInfo: "يتيح لنا تحديد هدفك تخصيص وجباتك وتمارينك اليومية.",
    password: 'كلمة المرور',
    passwordPlaceholder: 'أدخل كلمة المرور',
    login: 'تسجيل الدخول',
    register: 'تسجيل',
    registerNewAccount: 'إنشاء حساب جديد',
    loginToYourAccount: 'تسجيل الدخول إلى حسابك',
    or: 'أو',
    completeRegistration: 'إكمال التسجيل',
    welcomeGuestTitle: 'مرحباً بك في ny11',
    welcomeGuestBody: 'للحصول على خطة مخصصة، يرجى تسجيل الدخول أو إنشاء حساب جديد. سنقوم بإرشادك خلال بضع خطوات سريعة لإعداد ملفك الشخصي.',
    loginOrRegister: 'تسجيل الدخول / تسجيل',
    loginToContinue: 'يرجى تسجيل الدخول لاستخدام هذه الميزة.',
    registrationNote: 'جميع المعلومات التي تقدمها سيتم استخدامها من قبل خبرائنا لتقديم خدمة مميزة وصحيحة لذلك يرجى وضع بيانات دقيقة لك.',

    // Nav
    dashboard: 'الرئيسية',
    experts: 'الخبراء',
    activeChats: 'المحادثات',
    market: 'المتجر',
    stats: 'الإحصائيات',
    settings: 'الإعدادات',

    // Dashboard
    myProfile: 'ملفي الشخصي',
    age: 'العمر',
    weight: 'الوزن',
    height: 'الطول',
    todaysPlan: "خطة اليوم",
    weightLoss: 'خسارة الوزن',
    weightGain: 'زيادة الوزن',
    muscleBuild: 'بناء العضلات',
    fitness: 'اللياقة العامة',
    maintenance: 'الحفاظ على الوزن',
    finishSetup: 'إنهاء الإعداد',
    mealDetails: 'تفاصيل الوجبة',
    breakfast: 'الفطور',
    lunch: 'الغداء',
    dinner: 'العشاء',
    snacks: 'وجبات خفيفة',
    exercises: 'التمارين',
    setupProfileTitle: 'لنقم بإعداد ملفك الشخصي',
    setupProfileSubtitle: 'بناءً على هذه المعلومات، سنقوم بتخصيص وجباتك وتمارينك اليومية.',
    generatingPlan: 'جاري إنشاء خطتك...',
    generatingPlanDesc: 'نقوم بتخصيص جدولك اليومي بناءً على أهدافك.',
    
    // Chat
    connectWithExpert: 'تواصل مع خبير',
    connectWithExpertDesc: 'اختر مختصًا لبدء رحلتك الصحية المخصصة.',
    whyAnExpert: 'لماذا خبير؟',
    whyAnExpertDesc: 'يقدم خبراؤنا المعتمدون إرشادات فردية مصممة خصيصًا لجسمك وأهدافك. احصل على خطة فعالة، ومساءلة، والحافز الذي تحتاجه للنجاح.',
    viewProfile: 'عرض الملف الشخصي',
    backToExperts: 'العودة إلى الخبراء',
    yearsExp: 'سنوات خبرة',
    clientsHelped: 'عملاء',
    startChat: 'ابدأ المحادثة',
    typeAMessage: 'اكتب رسالة...',
    serviceQuote: 'عرض سعر الخدمة',
    accept: 'قبول',
    decline: 'رفض',
    yourActiveChats: 'محادثاتك النشطة',
    selectAChat: 'اختر محادثة للمتابعة.',
    
    // Market
    shoppingCart: 'سلة التسوق',
    cartIsEmpty: 'سلة التسوق فارغة.',
    total: 'المجموع:',
    checkout: 'الدفع',
    add: 'إضافة',
    ingredients: 'المكونات',
    nutritionFacts: 'الحقائق الغذائية',
    caution: 'تنبيه',
    servingSize: 'حجم الحصة',
    energy: 'الطاقة',
    protein: 'البروتين',
    carbohydrates: 'الكربوهيدرات',
    fat: 'الدهون',
    addToCart: 'أضف للسلة',

    // Stats
    yourProgress: 'تقدمك',
    overallAdherence: 'الالتزام العام',
    weeklyAdherence: 'الالتزام الأسبوعي',
    rechartsPlaceholder: 'سيتم عرض الرسم البياني هنا باستخدام مكتبة Recharts.',

    // Settings
    profileInfo: 'معلومات الملف الشخصي',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    preferences: 'التفضيلات',
    theme: 'المظهر',
    light: 'فاتح',
    dark: 'داكن',
    language: 'اللغة',
    english: 'English',
    arabic: 'العربية',
    logout: 'تسجيل الخروج',
    deleteAccount: 'حذف الحساب',
    deleteAccountConfirm: 'هل أنت متأكد من رغبتك في حذف حسابك؟ هذا الإجراء نهائي ولا يمكن التراجع عنه.',
    accountDeleted: 'تم حذف الحساب بنجاح.',
    testNotification: 'اختبار إشعار',
    
    // Notifications
    newMessageFrom: 'رسالة جديدة من {name}',
    planUpdatedTitle: 'تم تحديث الخطة!',
    planUpdatedBody: 'خطتك الجديدة متاحة في لوحة التحكم.',
    appointmentReminderTitle: 'موعد قادم',
    appointmentReminderBody: 'لديك اجتماع مع مدربك خلال 15 دقيقة.',

    // Admin Dashboard
    adminDashboard: 'لوحة تحكم المشرف',
    accountManagement: 'إدارة الحسابات',
    coachManagement: 'إدارة المدربين',
    storeManagement: 'إدارة المتجر',
    paymentManagement: 'إدارة المدفوعات',
    contentManagement: 'إدارة المحتوى',
    aiConfig: 'إعدادات المدرب الذكي',
    users: 'المستخدمون',
    coaches: 'المدربون',
    existingCoaches: 'المدربون الحاليون',
    addNewCoach: 'إضافة مدرب جديد',
    specialty: 'التخصص',
    bio: 'السيرة الذاتية',
    experience: 'الخبرة (سنوات)',
    clients: 'العملاء',
    avatarUrl: 'رابط الصورة الرمزية',
    addNewItem: 'إضافة عنصر جديد',
    itemName: 'اسم العنصر',
    description: 'الوصف',
    price: 'السعر',
    imageUrl: 'رابط الصورة',
    category: 'الفئة',
    meal: 'وجبة',
    drink: 'مشروب',
    addCoach: 'إضافة مدرب',
    addItem: 'إضافة عنصر',
    updateItem: 'تحديث العنصر',
    paymentsInfo: 'ميزات إدارة المدفوعات ستتوفر قريبًا.',
    confirmDelete: 'هل أنت متأكد أنك تريد حذف هذا العنصر؟',
    bannerImages: 'صور البنر',
    addNewImage: 'إضافة صورة جديدة',
    textContentManagement: 'إدارة المحتوى النصي',
    englishContent: 'المحتوى الإنجليزي',
    arabicContent: 'المحتوى العربي',
    roadmap: 'خارطة الطريق',
    roadmapTitle: 'خارطة طريق تطبيق NY11',
    exportPdf: 'تصدير كملف PDF',
    q1Title: 'الربع الأول 2024: التأسيس والإطلاق',
    q1Desc: 'إطلاق واجهة المستخدم الأساسية، الملفات الشخصية، المتجر الأساسي، ونظام المحادثة الأولي.',
    q2Title: 'الربع الثاني 2024: التكامل المالي والتقني',
    q2Desc: 'بوابة دفع إلكترونية كاملة (Visa/Mastercard)، محادثة فورية، وإشعارات متقدمة.',
    q3Title: 'الربع الثالث 2024: الذكاء الاصطناعي والتخصيص',
    q3Desc: 'تحليل صور الوجبات بالذكاء الاصطناعي، إنشاء خطط تلقائية ذكية، ومكالمات الفيديو.',
    q4Title: 'الربع الرابع 2024: التوسع والمجتمع',
    q4Desc: 'تحديات المجتمع، قوائم المتصدرين، الربط مع الساعات الذكية، وتطبيقات الجوال الأصلية.',
    homePageManagement: 'إدارة الصفحة الرئيسية',
    manageHeroTitle: 'العنوان الرئيسي',
    manageHeroSubtitle: 'العنوان الفرعي',
    heroImage: 'رابط صورة البداية',
    footerManagement: 'إدارة الفوتر',
    manageFooterDesc: 'وصف الفوتر',
    footerCopyright: 'نص حقوق النشر',
    enText: 'النص الإنجليزي',
    arText: 'النص العربي',
    updateCoach: 'تحديث المدرب',
    editCoach: 'تعديل المدرب',
    
    // AI Admin
    question: 'السؤال',
    answer: 'الإجابة',
    keywords: 'كلمات مفتاحية (مفصولة بفاصلة)',
    addNewQA: 'إضافة سؤال وجواب',
    existingQA: 'الأسئلة والأجوبة الحالية',
    addQA: 'إضافة',
    updateQA: 'تحديث',

    // Guided Tour
    tourWelcomeTitle: 'مرحباً بك في NY11!',
    tourWelcomeBody: 'لنقم بجولة سريعة لنوضح لك الميزات الرئيسية للتطبيق.',
    tourWelcomeBodyGuest: "لنقم بجولة سريعة لنرى ما يمكنك فعله. لفتح خطتك المخصصة، ستحتاج إلى إنشاء حساب.",
    tourPlanTitle: 'خطتك اليومية',
    tourPlanBody: 'هنا ستجد وجباتك وتمارينك المخصصة لهذا اليوم. أكملها وحقق أهدافك!',
    tourLoginPromptTitle: "خطتك المخصصة",
    tourLoginPromptBody: "بعد تسجيل الدخول، ستظهر وجباتك وتمارينك اليومية هنا. كل شيء يبدأ بإنشاء ملفك الشخصي!",
    tourNavTitle: 'تنقل سهل',
    tourNavBody: 'استخدم هذا الشريط للتبديل بين الأقسام الرئيسية للتطبيق في أي وقت.',
    tourExpertsTitle: 'ابحث عن خبير',
    tourExpertsBody: 'تصفح خبرائنا المعتمدين وابدأ محادثة للحصول على خطة صحية مخصصة.',
    tourMarketTitle: 'المتجر الصحي',
    tourMarketBody: 'اطلب وجبات ومشروبات صحية من مطبخنا، تصلك مباشرة.',
    tourSettingsTitle: 'إدارة الإعدادات',
    tourSettingsBody: 'حدّث ملفك الشخصي، وغيّر المظهر، وأدر تفضيلاتك من هنا.',
    tourFinish: 'إنهاء',
    tourSkip: 'تخطي',
  }
}

export type TranslationSet = typeof TRANSLATIONS[Language.EN];
